# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI on push

on:
  push:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: frontend

    strategy:
      matrix:
        node-version: [22]
        mongodb-version: [4.4.0]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && cd ../backend && npm ci && cd ../frontend && npm run library
    - run: npm run build --if-present
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: cd ../backend && nohup npm run start:testServer &
      env: 
        SECRET: ${{ secrets.SECRET }}
        PORT: 3001
        IMAGEURL: 'images'
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        working-directory: frontend
        start: npm start
        wait-on: http://localhost:3000
        wait-on-timeout: 300
        spec: cypress/e2e/*
      
  backend:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: backend

    strategy:
      matrix:
        node-version: [22]
        mongodb-version: [4.4.0]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci 
    - run: npm run library
    - run: npm run test-gh-bacterium
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
    - run: npm run test-gh-test
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'    
    - run: npm run test-gh-user
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
    - run: npm run test-gh-credit
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
    - run: npm run test-gh-game
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
    - run: npm run test-gh-case
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
    - run: npm run test-gh-game-testing
      env: 
        SECRET: ${{ secrets.SECRET }}
        IMAGEURL: 'images'
  
  build:
    name: 'Publish to dockerhub'
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hybakteeripeli/app:latest
      
