# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: frontend

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: [4.0, 4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && cd ../backend && npm ci && cd ../frontend
    - run: npm run build --if-present
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}  
    - run: cd ../backend && nohup npm run start:testServer &
      env: 
        SECRET: 'salainen'
        PORT: 3001
        IMAGEURL: 'images'
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npm start
        working-directory: frontend
        wait-on: http://localhost:3000
        wait-on-timeout: 300
  backend:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: backend

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: [4.0, 4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci
    - run: npm run test-githubactions
      env: 
        PORT: 3001
        SECRET: 'salainen'
        IMAGEURL: 'images'
